### ISSUE TITLE
Spacing of Capitalizations

### ISSUE THREAD

**Issue by AnilRh** [oe/sourcetree-alfred-workflow#1]
Thanks for the great work on this workflow. 

**Issue**
For a bookmark labeled "AMD Something" in order to find it in Alfred you need to search for "A M D So...", searching for "AMD" doesn't find anything.

**Hack**
I removed the line of code causing the issue - it works great again:
`.replacingOccurrences(of: #"([A-Z])"#, with: " $1", options: .regularExpression, range: nil)
`

**Cause**
I think SourceTree might have changed something recently - I had been using the [old Python2 workflow](https://github.com/yourtion/Alfred_SourceTree) and it recently started having the same issue (however for the past many years before it worked fine).

**Suggestion**
Perhaps consider making the addition of a space to capitalized letters an option. It's not clear to me what use cases this line of code is for - perhaps the regex should be changed to only add a space if the previous character is a lower case letter?

**Comment by oe** [comment]
Thanks for your feedback, I'll try to implement the searching function via swift instead of Alfred's filter

**Comment by oe** [comment]
Hi, I just fixed this issue, and added some features:

1. add fuzzy search(ignore case and diacritic)
2. compile script to speed up workflow response time for Intel Macs via `st $compile`

click <https://github.com/oe/sourcetree-alfred-workflow/raw/main/SourceTree.alfredworkflow> to download the latest workflow

**Comment by AnilRh** [comment]
That works wonderfully, thanks @oe!

**Comment by oe** [comment]
There is more, with the latest release v0.1.9 you can open repo in your code editor directly via `cmd` + `enter`. It uses VS Code by default, you can [custom it to you own favorite editor](https://github.com/oe/sourcetree-alfred-workflow#custom-your-perferred-code-editor)
