### ISSUE TITLE
[Usage] Similar Product Functionality Implementation?

### ISSUE THREAD

**Issue by Wxh16144** [oe/sourcetree-alfred-workflow#5]
Hello great developers

I've been using this project for a while and it works great, but recently I switched from sourcetree to [fork CUI](https://git-fork.com/) client and I was going to fork your repository to make changes, but I don't know `.swift` language development. Can you help me? Or give me some advice. 

Thank you very much, and sorry in advance if I'm bothering you.

**Comment by oe** [comment]
You don't need to understand the Swift programming language.

Here are the key concepts of this workflow:
1. get the repos managed by SourceTree or other git applications. For example, SourceTree stores this in the file `~/Library/Application Support/SourceTree/browser.plist'.
2. read the repos info and convert it to an alfred data structure

**Comment by oe** [comment]
> You don't need to understand the Swift programming language.
> 
> Here are the key concepts of this workflow:
> 
> 1. get the repos managed by SourceTree or other git applications. For example, SourceTree stores this in the file `~/Library/Application Support/SourceTree/browser.plist'.
> 2. read the repos info and convert it to an alfred data structure

and the final step: print the result, using `print` for swift, `console.log` for javascript, `echo` for sh or php, etc
